"""empty message

Revision ID: a0bd322c5a4c
Revises: 64f789c014c4
Create Date: 2021-11-11 17:59:28.847777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bd322c5a4c'
down_revision = '64f789c014c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptocurrency', sa.Column('gecko', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptocurrency', 'gecko')
    # ### end Alembic commands ###
