"""empty message

Revision ID: 64f789c014c4
Revises: 9df5ce0d0a92
Create Date: 2021-11-10 16:53:35.847170

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")



# revision identifiers, used by Alembic.
revision = '64f789c014c4'
down_revision = '9df5ce0d0a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Watchlist_Crypto',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrency.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'crypto_id')
    )

    # if environment == "production":
    #         op.execute(f"ALTER TABLE Watchlist_Crypto SET SCHEMA {SCHEMA};")

    op.drop_table('association')
    op.add_column('cryptocurrency', sa.Column('history', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptocurrency', 'history')
    op.create_table('association',
    sa.Column('watchlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crypto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrency.id'], name='association_crypto_id_fkey'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], name='association_watchlist_id_fkey'),
    sa.PrimaryKeyConstraint('watchlist_id', 'crypto_id', name='association_pkey')
    )
    op.drop_table('Watchlist_Crypto')
    # ### end Alembic commands ###
