"""empty message

Revision ID: cbc568da1dbb
Revises: 0e6cdb45c554
Create Date: 2021-11-09 21:14:49.428542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc568da1dbb'
down_revision = '0e6cdb45c554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cash', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cash')
    # ### end Alembic commands ###
