"""empty message

Revision ID: 4abe5ea83d67
Revises: c8ec66e48e29
Create Date: 2021-11-08 15:34:07.453939

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '4abe5ea83d67'
down_revision = 'c8ec66e48e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE cryptocurrency SET SCHEMA {SCHEMA};")
        
    op.create_foreign_key(None, 'transactions', 'cryptocurrency', ['crypto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_table('cryptocurrency')
    # ### end Alembic commands ###
